name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: CMake Configure
      run: cmake -Bbuild
    - name: CMake Build
      run: cmake --build build    

